#!/bin/sh

set -e
umask 0002

OPTIONS="--show - --default all --select-base /usr/libexec/device/system/syslog/protocol.txt --select protocol --symlink-base /usr/lib/firewalld/zones --symlink-suffix=.xml --symlink zone"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

